replicaCount: 1

image:
  sql:
    repository: microsoft/mssql-server-linux
    tag: 2017-CU13
    pullPolicy: IfNotPresent
  mongo:
    repository: mongo
    tag: 3.4-xenial
    pullPolicy: IfNotPresent   
  azurite:
    repository: arafato/azurite
    tag: "2.6.5"
    pullPolicy: IfNotPresent
  pg:
    repository: postgres
    tag: "12-alpine"
    pullPolicy: IfNotPresent   

service:
  sql:
    type: ClusterIP
    port: 1433
  mongo:
    type: ClusterIP
    port: 27017
  azurite:
    type: ClusterIP
    port: 10000
  pg:
    type: ClusterIP
    port: 5432

volumes:
  sql:
    storage: 5Gi
    storageClass: default
  postgresql:
    storage: 5Gi
    storageClass: default
  mongo:
    storage: 5Gi
    storageClass: default

resources: {}

nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}
