{{- $name := include "tt-popularproducts.fullname" . -}}
{{- $sqlsrv := .Values.inf.db.popularproducts.host -}}
{{- $sqlport := .Values.inf.db.popularproducts.port -}}
{{- $sqldb := .Values.inf.db.popularproducts.catalog -}}
{{- $sqluser := .Values.inf.db.popularproducts.user -}}
{{- $sqlpwd := .Values.inf.db.popularproducts.pwd -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-init-{{ $name }}"
  labels:
    app: {{ template "tt-popularproducts.name" . }}
    chart: {{ template "tt-popularproducts.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  dbserver: {{ $sqlsrv }}
  dbuser: {{ $sqluser }}
  dbpassword: {{ $sqlpwd }}
  dbcatalog: {{ $sqldb }}
