replicaCount: 1
applicationName: tailwindtraders

image:
  repository: tailwindtradersacr.azurecr.io/stock.api
  tag: prod
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
  requests:
    cpu: "100m"

nodeSelector:
  "kubernetes.io/os": linux

tolerations: []

affinity: {}

env:
  configmap:
    - name: APPLICATION_INSIGHTS_IKEY
    - name: ISSUER
    - name: SECURITYKEY
    - name: sql_server_url
    - name: sql_user_name
    - name: sql_user_password
  values: {}

probes:
  liveness:
    path: /liveness
    initialDelaySeconds: 100
    periodSeconds: 30
    port: http
