{{- $name := include "tt-stock.fullname" . -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "tt-stock.name" . }}
    chart: {{ template "tt-stock.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  APPLICATION_INSIGHTS_IKEY:  {{ .Values.inf.appinsights.id }}
  sql_server_url: "jdbc:postgresql://{{ .Values.inf.db.stock.host }}:{{ .Values.inf.db.stock.port }}/{{ .Values.inf.db.stock.catalog }}"
  sql_user_name: {{ .Values.inf.db.stock.user }}
  sql_user_password: {{ .Values.inf.db.stock.pwd }}
  ISSUER: {{ .Values.sec.issuer }}
  SECURITYKEY: {{ .Values.sec.securityKey }}
  
