{{- $name := include "infrastructure.fullname" . -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "{{ $name }}-stockdb"
  labels:
    app: {{ template "infrastructure.name" . }}
    chart: {{ template "infrastructure.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "infrastructure.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "infrastructure.name" . }}
        release: {{ .Release.Name }}
        component: stockpg
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.pg.repository }}:{{ .Values.image.pg.tag }}"
          imagePullPolicy: {{ .Values.image.pg.pullPolicy }}
          env:
          - name: POSTGRES_PASSWORD
            value: Passw0rd1!
          - name: POSTGRES_USER
            value: ttadmin
          - name: POSTGRES_DB
            value: stockdb
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: postgresql-volume
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
