apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: {{ template "infrastructure.name" . }}
    chart: {{ template "infrastructure.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.mongo.type }}
  ports:
    - port: {{ .Values.service.mongo.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "infrastructure.name" . }}
    release: {{ .Release.Name }}
    component: mongo
