apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.volumes.postgresql.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumes.postgresql.storage }}