apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.volumes.mongo.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumes.mongo.storage }}