apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.volumes.sql.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volumes.sql.storage }}